<?php

$filters_to_show = [
    'Internal Hard Drives' => ['HDD size','HDD capacity','HDD speed','Operating voltage','Interface'],
    'Internal Solid State Drives' => ['SSD form factor', 'SSD capacity'],
    'Mobile Device Chargers' => ['Product colour','Cable length','Maximum power','Cables included','AC adapter output current','Quick charge','Wireless charging'],
    'Mobile Device Keyboards' => ['Device interface','Product colour','Brand compatibility','Backlight'],
    'Notebook Cases' => ['Maximum screen size','Case type','Material','Product main colour','Brand compatibility'],
    'Wireless Routers' => ['LED indicators','On/off switch','Product type','Antenna type','Power source type','Wi-Fi standards','Ethernet LAN (RJ-45) ports','USB port'],
    'Computer Monitors' => ['Display diagonal','Swivelling','Tilt angle range','Height adjustment','Panel mounting interface','Audio output',
        'Audio input','Display brightness (typical)','Contrast ratio (dynamic)','Display number of colours','Maximum refresh rate','Screen shape',
        'Display technology','HD type','Response time','Native aspect ratio','Display resolution','HDMI','DVI port','Built-in USB hub','Built-in camera',
        'Built-in speaker(s)','AMD FreeSync','3D','Display','Supported video modes','Built-in microphone','NVIDIA G-SYNC'],
    'Keyboards' => ['Wrist rest','Mouse included','Device interface','Connectivity technology','Keyboard form factor','Pointing device'],
    'Mice' => ['Device interface','Product colour','Form factor','Movement resolution','Buttons quantity'],
    'PCs/Workstations' => ['Processor manufacturer','Audio chip','Operating system installed','Motherboard chipset','Product colour','Placement supported',
        'Power supply','Processor model','Internal memory type','Internal memory','PCI Express configurations','Memory layout (slots x size)','Processor socket',
        'Processor frequency','Processor cores','Discrete graphics adapter','On-board graphics adapter','Card reader integrated','Optical drive type',
        'Storage media','Total storage capacity','Bluetooth','Wi-Fi standards'],
    'Gaming Controllers' => ['Device type','Connectivity technology','Gyroscope','Accelerometer'],
    'Headphones & Headsets' => ['Product type','Noise-canceling','Wearing style','Microphone type','Connectivity technology'],
    'Notebooks' => ['Ethernet LAN','Wi-Fi standards','Pointing device','Operating system installed','Speaker power','Discrete graphics adapter','Product type',
        'Processor frequency','Processor model','Processor manufacturer','HD type','Panel type','Touchscreen','Display resolution','Display diagonal',
        'Form factor','Processor cores','On-board graphics adapter','Maximum internal memory','Optical drive type','Flash memory','Storage media',
        'Total storage capacity','Internal memory','3D','Virtual Reality (VR) ready','NFC key','Microphone in','Audio system','Quick charge',
        'Discrete GPU manufacturer','Face recognition'],
    'Speaker Sets' => ['RMS rated power'],
    'Streaming Devices' => ['Maximum video resolution','Mounting type','Built-in microphone','Maximum frame rate','Auto focus','Supported video modes','Full HD'],
    'Tablets' => ['Display diagonal','Device type','Platform','Wi-Fi standards','Mobile network connection','Front camera','Display resolution','Processor cores',
        'Processor frequency','Processor model','Built-in microphone','Video recording','Auto focus','Rear camera type','Rear camera','Speaker power','Audio system',
        'Number of microphones','Number of built-in speakers','Built-in speaker(s)','Thermal Design Power (TDP)','Graphics adapter','Storage media','Compatible memory cards',
        'Internal storage capacity','Internal memory','Display technology','On-board graphics adapter','Fast charging'],
    'TVs' => ['Display diagonal','PC in (D-Sub)','Works with Amazon Alexa','Works with Samsung Bixby','Display resolution','Tuner type','Smart TV',
        'Panel mounting interface','Built-in speaker(s)','3D','Operating system installed','Processor cores','4K Ultra HD upscaling','Internet TV','Plug and Play'],
    'Wearables' => ['Display diagonal','USB port','Gyroscope','Military standard','GPS (satellite)','GLONASS','Wi-Fi standards','Heart rate monitor',
        'Accelerometer','Built-in camera','Display type','Display resolution','RAM capacity','Flash memory','Wireless charging']
];